name: try-jupyter
channels:
- conda-forge
dependencies:
- python =3.11
- mamba
- pydata-sphinx-theme
- myst-parser
- bqplot
- ipycanvas >=0.9.1
- ipyleaflet
- ipympl >=0.8.2
- ipywidgets >=8.1.1,<9
- jupyterlab >=4.0.9,<5
- jupyterlab-language-pack-fr-FR
- jupyterlab-language-pack-zh-CN
- jupyterlab-fasta >=3.3.0,<4
- jupyterlab-geojson >=3.4.0,<4
# currently broken: https://github.com/jupyterlab-contrib/jupyterlab-tour/issues/82
# - jupyterlab-tour
- jupyterlab-night
- jupyterlite-core =0.2.1
- jupyterlite-pyodide-kernel =0.2.0
- jupyterlite-sphinx >=0.10.0,<0.11
- notebook >=7.0.6
- pip
- plotly >=5,<6
- pip:
  - jupyterlite-xeus-sqlite==0.2.1
  - jupyterlab-open-url-parameter
